version: "3.9"

services:
  nats-server:
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
        reservations:
          cpus: "0.5"
          memory: 300M
    ports:
      - "8080:8080"
    environment:
      GIN_MODE: release
      NATS_URL: nats:4222
  nats-agent:
    container_name: agent
    build:
      context: .
      dockerfile: agent/Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
        reservations:
          cpus: "0.5"
          memory: 300M
    environment:
      NATS_URL: nats:4222
  nats:
    image: nats:2.11
    container_name: nats
    restart: unless-stopped
    command: ["-js", "-m", "8222", "--store_dir", "/data"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "4222"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  nats-data:

